import Head from 'next/head';
import React, {useState} from "react";
import Link from 'next/link';

import {BsFillMoonStarsFill,BsFillBootstrapFill} from "react-icons/bs";
import {AiOutlineArrowDown,AiFillTwitterCircle,AiFillLinkedin,AiFillInstagram,AiFillGithub,AiFillHtml5,} from "react-icons/ai";
import {DiCss3,DiReact} from "react-icons/di";
import {SiJavascript,SiTailwindcss} from "react-icons/si";
import {TbBrandReactNative,TbBrandNextjs} from "react-icons/tb";
import {FaGitAlt} from "react-icons/fa";
import Image from 'next/image';
import profile from '../../public/3.jpg';
import Navbar from './Navbar'
import Sidebar from './Sidebar'
import Projects from './Projects';
import Contact from './Contact';
import Footer from './Footer';
 
export default function Home() {
  
const scroll=()=>{
  window.scrollTo({
    top: document.getElementById(2).offsetTop,
    behavior: 'smooth'
  });
}
  const [darkMode,setDarkMode] = useState(false)

  const handleDarkMode =()=>{
    setDarkMode(!darkMode);
  }

  return(
    <div id="0" className= {darkMode ? "dark": ""}>
      <Head >
        <title>Souleymane Djibrine Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* px-10 md:px-20 lg:px-30 for the main*/}
      <main className='bg-white  dark:bg-gray-900'>
        <section     className="min-h-screen pt-20 mt-15" >
        <Navbar  darkModeHandler ={handleDarkMode}/>
          <div  className='text-center p-10'>
          <div className='md:flex text-center justify-center mt-20'>
          <h2 className='text-5xl py-2  text-green-600 font-medium md:text-6xl leading-50'>Souleymane</h2>
          <h2 className='text-5xl py-2 ml-2 text-green-600 font-medium md:text-6xl leading-50 '>Djibrine</h2>
          </div>

         <h3 className='text-2xl py-2 md:text-3xl text-green-700'>Frontend developer and designer.</h3>
         <p className='text-md pt-2 pb-5 leading- text-gray-800 md:text-xl max-w-md mx-auto dark:text-white ' >If you need programming or design content services, I am a freelancer ready to help. Let's collaborate and get started today!</p>
         <button onClick={scroll} className="bg-transparent hover:bg-green-500 text-black dark:text-white font-semibold hover:text-white py-2 px-4 border border-green-500 hover:border-transparent rounded">
         PROJECTS
           </button>

          </div>
        
          <Sidebar/>
          <div className=' duration-200 hover:scale-105 mb-10 rounded-full w-80 h-80  p-20 mx-auto overflow-hidden xl:w-96 xl:h-96'>
        <Image  className ="rounded-full shadow-3xl border-2" src={profile} alt ="profile-image"/>
          </div>
        </section>
     <section>
<div className='text-center mb-100'>
<div>
  <h2 className=' text-center mt-20 mb-3 text-3xl inline border-b-4 border-green-700  text-green-600 font-medium md:text-4xl'>ABOUT ME</h2>
  <p className='max-w-md mx-auto mb-10 text-gray-900 mt-6 dark:text-white px-4 md:text-lg'>Here, you'll find additional information about me, my current skills, and the work that I do, with a focus on <strong className='dark:text-green-600'>programming</strong> and <strong className='dark:text-green-600'>technology</strong>.</p>
  </div>
 <div id="1" className='mt-8 dark:text-white'>
<p  className='max-w-md mx-auto px-4 md:text-lg'>
I'm Souleymane, a <strong className='dark:text-green-600' >frontend developer</strong> with <strong className='dark:text-green-600'>1.5</strong> years of experience creating engaging and user-friendly websites. My passion is designing and developing beautiful, functional websites that meet my clients' needs and exceed their expectations.
</p>
<p className='max-w-md mx-auto px-4 py-2 md:text-lg  '>
My skills include <strong className='dark:text-green-600'>HTML, CSS, JavaScript,</strong> and other related <strong className='dark:text-green-600'>technologies</strong>. I'm always learning and staying up-to-date with the latest trends in <strong className='dark:text-green-600'>web development</strong> to ensure the websites I build are functional and perform well across different platforms and devices.
</p>
<p className='max-w-md mx-auto px-4 pb-2 md:text-lg'>
I enjoy collaborating with clients to understand their unique needs and goals, and working with them to create the best possible solutions. When I'm not coding, I'm exploring new technologies, reading tech blogs, or enjoying the great outdoors.
</p>
<p className='max-w-md mx-auto px-4 md:text-lg' >Check out some of the work I've done in the <strong className='dark:text-green-600'>projects</strong> section. If you're interested in working with me, please don't hesitate to get in touch!</p>
</div>
<div className=''>
  <h2 className=' text-center mt-20 mb-10 text-2xl  text-green-600 font-medium md:text-3xl' >My Skills</h2>

<table className='mx-auto text-center md:w-[50%] dark:text-white'>
  <tbody>
  <tr className=''>
    <td>
    <span><AiFillHtml5 className = "mx-auto" size= {50}/></span>
    <p className = "mb-5 mt-1">HTML5</p>
    </td>
    <td>
    <span><DiCss3 className = "mx-auto" size= {50}/></span>
    <p className = "mb-5 mt-1">CSS</p>
    </td>
    <td>
    <span><SiJavascript className = "mx-auto" size= {50}/></span>
    <p className = "mb-5 mt-1">JAVASCRIPT + ES6</p>
    </td>
  </tr>
  <tr>
  <td>
  <span><DiReact className = "mx-auto" size= {50}/></span>
    <p className = "mb-5 mt-1">REACT</p>
  </td>
  <td>
  <span><SiTailwindcss className = "mx-auto" size= {50}/></span>
    <p className = "mb-5 mt-1">TAILWIND CSS</p>
  </td>
  <td>
  <span><BsFillBootstrapFill className = "mx-auto" size= {50}/></span>
    <p className = "mb-5 mt-1">BOOTSTRAP</p>
  </td>
  </tr>
  <tr>
  <td><span><TbBrandReactNative className = "mx-auto" size= {50}/></span>
    <p className = "mb-5 mt-1">REACT NATIVE</p></td>
  <td>
  <span><FaGitAlt className = "mx-auto" size= {50}/></span>
    <p className = "mb-5 mt-1">GIT</p>
  </td>
  <td>
    <span><TbBrandNextjs className = "mx-auto" size= {50}/></span>
    <p>NEXT JS</p>
  </td>
  </tr>
  </tbody>
</table>
</div>
</div>
    
     </section>

     <section>
    <Projects/>
     </section>
     <section>
    <Contact/>
     </section>

     <section>
      <Footer/>
     </section>
      </main>
    </div>
  )
}
